# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e7c616c5d0f9773e94fadefb9097aedb9a368570748c5d153d22d61738c67e464dfd2c3c39c506aaee462083853bfb59ec779b05a46c48e7dfa4dc45bd3c295

test:
  secret_key_base: edf851ff08afcc76f0ec1309fc737aea87bb55d54a6ca13a2dd22302ccc5f9c3204028c3e6dc392b0232a96ad3bd82a308c3a26670cfbff954c76656214ffc6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
